# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BLOG
email: yusuf@kanunsuzlar.com
description:  Dağların eşkıyası, şehirlerin kabadayısı, köyün ağası - değil tabi. Sadece standart bir araştırmacı.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.kanunsuzlar.com" # the base hostname & protocol for your site
twitter_username: kanun_suz
github_username:  kanunsuz

# Build settings
markdown: kramdown
